[theme]
base                     = "dark"
primaryColor             = "#00C8FF"
backgroundColor          = "#08091C"
secondaryBackgroundColor = "#0D1128"
textColor                = "#EEF2FF"
font                     = "sans serif"

[server]
headless             = true
enableCORS           = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
